### ISSUE TITLE
Intellisense in “Processing Language” Extension for VS Code not working 

### ISSUE THREAD

**Issue by pedroGerman** [TobiahZ/processing-vscode#93] opened 2021-02-14 02:58 UTC
Hi, I’m using “Processing Language” extension for Visual Studio Code in Windows, and I already did every step necessary in order to execute successfully a .pde file. The problem is, how can I configure the extension, so it could mark an possible warning/syntax error in a specific line automatically (like the actual Processing App does)? The next image shows a clear example of what I’m referring to.

![Processing APP   VS Code](https://user-images.githubusercontent.com/70279858/107867150-ce257d80-6e4e-11eb-92ca-4f3bfe5e3223.png)

As you can see, Processing (at left) does mark the error on the 11th line. But, when I try on VS Code (at right), the supposed error does not appear visible. It only checks for autocompletion, albeit not being working for highlighting issues in the code. 

I have installed Processing 3.0 for Windows (just in case this information may be useful to you). Thanks in advance!

**Comment by AvinZarlez** [comment] 2021-02-16 17:14
I believe this is a dupe of #4

**Closed as completed by AvinZarlez** 2021-02-16 17:14 UTC
